### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arvoelke** [arvoelke/delay2017#3]
- [x] Complete Voelker & Eliasmith 2017 citation (http://arxiv.org/abs/1708.08133)
 - [ ] Release nengolib==0.4.1
 - [x] "taking the dot-product of the neural activities with the full-rank weight matrix W" -> "taking the dot-product of the full-rank weight matrix W with the neural activities"
 - [x] "spike noise" -> "spike-noise"
 - [x] "infinitely-dimensional" -> "infinite-dimensional"
 - [x] Update Andreas citation
